language: rust
sudo: false

cache: cargo

matrix:
  include:
    - rust: stable
    - rust: nightly
  allow_failures:
    - rust: nightly

script:
  - cargo test

notifications:
  email:
    on_success: never
