language: rust
sudo: required
services:
  - docker

cache: cargo

matrix:
  include:
    - rust: stable
    - rust: nightly
  allow_failures:
    - rust: nightly

script:
  - cargo test
  # run interop tests
  - ./tower-grpc-interop/travis-interop.sh

notifications:
  email:
    on_success: never
