[package]
name = "tower-grpc-build"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
codegen = { git = "https://github.com/hawkw/codegen", branch = "eliza/prefixed-imports" }
prost-build = { git = "https://github.com/danburkert/prost" }