[package]
name = "tower-grpc-build"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
codegen = { git = "https://github.com/carllerche/codegen" }

[dependencies.prost-build]
git = "https://github.com/danburkert/prost"
rev = "2bcb494654ef1885c13eb234e0e235eae34b7999"