[package]
name = "tower-grpc-examples"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[[bin]]
name = "helloworld-server"
path = "src/helloworld/server.rs"

[[bin]]
name = "helloworld-client"
path = "src/helloworld/client.rs"

[[bin]]
name = "route-guide-server"
path = "src/routeguide/server.rs"

[[bin]]
name = "route-guide-client"
path = "src/routeguide/client.rs"

[dependencies]
futures = "0.1"
bytes = "0.4"
env_logger = "0.4"
log = "0.3"
http = "0.1"
tokio-core = "0.1"
tower = { git = "https://github.com/tower-rs/tower" }
tower-h2 = { git = "https://github.com/tower-rs/tower-h2" }
tower-grpc = { path = "../" }

# For the routeguide example
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.prost]
git = "https://github.com/danburkert/prost"
rev = "2bcb494654ef1885c13eb234e0e235eae34b7999"

[dependencies.prost-derive]
git = "https://github.com/danburkert/prost"
rev = "2bcb494654ef1885c13eb234e0e235eae34b7999"

[build-dependencies]
tower-grpc-build = { path = "../tower-grpc-build" }

[patch.crates-io]
http = { git = "http://github.com/hyperium/http", rev = "5f362a32278891672f428d570d46387fe6896a5d" }
