version: '3'
services:

  server-go:
    build:
      context: .
      dockerfile: Dockerfile-server-go
    ports: 
    - "10000:10000"

  client-tower:
    build:
      context: ..
      dockerfile: tower-grpc-examples/Dockerfile-interop-client
    command: --test_case=empty_unary --server_host="server-go" # this is the only one that works
    depends_on:
    - server-go